-- ====================================================
-- CREACIÓN E INICIALIZACIÓN DEL ESQUEMA DE DATOS
-- ====================================================
-- ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- CREATE USER sgsi IDENTIFIED BY pass123;
-- GRANT CONNECT, RESOURCE, DBA TO sgsi;

-- ==========================================
-- CREACIÓN DE TABLAS (Etapa de Diseño)
-- ==========================================

CREATE TABLE pacientes (
    id_paciente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni VARCHAR2(20) UNIQUE NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    telefono VARCHAR2(20),
    email VARCHAR2(100)
);

CREATE TABLE profesionales (
    id_profesional INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula VARCHAR2(50) UNIQUE NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    especialidad VARCHAR2(100) NOT NULL
);

CREATE TABLE turnos (
    id_turno INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente INTEGER NOT NULL,
    id_profesional INTEGER NOT NULL,
    fecha_hora TIMESTAMP NOT NULL,
    estado VARCHAR2(50) DEFAULT 'Pendiente',
    FOREIGN KEY (id_paciente) REFERENCES pacientes(id_paciente),
    FOREIGN KEY (id_profesional) REFERENCES profesionales(id_profesional)
);

CREATE TABLE historias_clinicas (
    id_historia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente INTEGER NOT NULL,
    id_profesional INTEGER NOT NULL,
    fecha_registro TIMESTAMP NOT NULL,
    observaciones VARCHAR2(4000) NOT NULL,
    FOREIGN KEY (id_paciente) REFERENCES pacientes(id_paciente),
    FOREIGN KEY (id_profesional) REFERENCES profesionales(id_profesional)
);

-- ==========================================
-- INSERCIÓN DE REGISTROS (Etapa de Pruebas)
-- ==========================================

-- Pacientes
INSERT INTO pacientes (dni, nombre, apellido, telefono, email) 
VALUES ('11223344', 'Juan', 'Pérez', '8888-1111', 'juan@email.com');

INSERT INTO pacientes (dni, nombre, apellido, telefono, email) 
VALUES ('55667788', 'María', 'Gómez', '8888-2222', 'maria@email.com');

-- Profesionales
INSERT INTO profesionales (matricula, nombre, apellido, especialidad) 
VALUES ('MED-001', 'Carlos', 'López', 'Medicina General');

INSERT INTO profesionales (matricula, nombre, apellido, especialidad) 
VALUES ('NUT-002', 'Ana', 'Martínez', 'Nutrición');

INSERT INTO profesionales (matricula, nombre, apellido, especialidad) 
VALUES ('PSI-003', 'Laura', 'Fernández', 'Psicología');

-- Turnos
INSERT INTO turnos (id_paciente, id_profesional, fecha_hora, estado) 
VALUES (1, 1, TO_TIMESTAMP('2026-06-15 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Atendido');

INSERT INTO turnos (id_paciente, id_profesional, fecha_hora, estado) 
VALUES (2, 2, TO_TIMESTAMP('2026-06-16 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Pendiente');

INSERT INTO turnos (id_paciente, id_profesional, fecha_hora, estado) 
VALUES (1, 3, TO_TIMESTAMP('2026-06-17 15:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Pendiente');

-- Historias Clínicas
INSERT INTO historias_clinicas (id_paciente, id_profesional, fecha_registro, observaciones) 
VALUES (1, 1, TO_TIMESTAMP('2026-06-15 09:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Paciente presenta cuadro febril leve. Se indica reposo.');

INSERT INTO historias_clinicas (id_paciente, id_profesional, fecha_registro, observaciones) 
VALUES (2, 2, TO_TIMESTAMP('2026-05-10 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Se ajusta plan calórico a 2000 kcal diarias.');

-- Guardamos los datos en la base de datos
COMMIT;

-- ==========================================
-- CONSULTAS REPRESENTATIVAS (SELECT)
-- ==========================================
-- Consultar el historial interdisciplinario de un paciente específico (Juan Pérez)
SELECT 
    p.nombre AS "Paciente", 
    p.apellido, 
    prof.especialidad AS "Disciplina",
    prof.apellido AS "Profesional",
    hc.fecha_registro AS "Fecha", 
    hc.observaciones AS "Evolución Clínica"
FROM 
    historias_clinicas hc
JOIN pacientes p ON hc.id_paciente = p.id_paciente
JOIN profesionales prof ON hc.id_profesional = prof.id_profesional
WHERE 
    p.dni = '11223344'
ORDER BY 
    hc.fecha_registro DESC;

-- ==========================================
-- BORRADO DE REGISTROS (DELETE)
-- ==========================================
-- Cancelar/Borrar un turno erróneo
DELETE FROM turnos WHERE id_turno = 2;

-- Confirmar el borrado
COMMIT;